# Shofar v2.0 Example Configuration
# Copy this file to 'config.yaml' and customize for your environment.

# Network settings for the CSNP layer
network:
  node_id: "shofar-node-alpha-01"
  bootstrap_peers:
    - "192.168.1.100:8443"
    - "192.168.1.101:8443"
  timeout_ms: 5000

# Policy Studio configuration
policy_studio:
  # Path to the library of ethical doctrines for the linter
  doctrine_path: "./policies/doctrines/un_declarations.yaml"
  # Directory where compiled policies are stored
  compiled_policy_dir: "./policies/compiled/"

# ARTC (Affective Red Team Core) settings
artc:
  # Path to the signed ethical dataset
  dataset_path: "/var/data/shofar/ethical_dataset_v2.dat"
  # Risk score threshold for issuing an automatic veto
  veto_threshold: 0.95

# Telemetry and Observability (OpenTelemetry)
telemetry:
  enabled: true
  exporter: "otlp_grpc" # or "console", "otlp_http"
  endpoint: "http://localhost:4317"
  service_name: "ShofarNode-Primary"

# Logging configuration
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "/var/log/shofar/node.log"
